feat: fetch all native stakers w/ history
marinade-finance/solana-snapshot-manager pull request #28
Opened 2023-08-30 12:49 UTC by butonium

2023-08-30 14:43 UTC, martinkrecek requested changes
Commenting mostly on data types, otherwise looks ok.

2023-08-30 14:43 UTC, martinkrecek commented on src/stakers/stakers.controller.ts
> +    }
(non-blocking/optional comment) This is an exact copy-paste of the validation in `getNativeStakes` below, I'd consider wrapping it in a helper function which accepts the `query` as a parameter and performs the checks.

2023-08-30 14:43 UTC, martinkrecek commented on src/stakers/stakers.controller.ts
> +    type: NativeStakeBalanceDto,
Using `NativeStakeBalanceDto` and `NativeStakeBalancesDto` can be dangerous exactly for these reasons, this line is supposed to contain `NativeStakeBalancesDto` (the newly added DTO). This line should definitely be fixed, but I'd also recommend renaming the new DTO to something like `NativeStakeAllBalancesDto` or `AllNativeStakeBalancesDto` to differentiate it a bit more.

2023-08-30 14:43 UTC, martinkrecek commented on src/stakers/stakers.service.ts
> +  ): Promise<{ [key: string]: NativeStakeBalanceDto[] } | null> {
```suggestion
  ): Promise<NativeStakeBalancesDto | null> {
```

Haven't tested it, but shouldn't this work too?

2023-08-30 14:43 UTC, martinkrecek commented on src/stakers/stakers.service.ts
> +    const ownerBalances: { [key: string]: NativeStakeBalanceDto[] } = {};
Same case like in the comment on the function signature above, using `NativeStakeBalancesDto` should be ok here.

2023-08-31 13:29 UTC, martinkrecek approved these changes

2023-09-05 11:55 UTC, janlegner approved these changes

2023-09-05 11:56 UTC, merged